name: Publicar Exkyn.Notifications.Email no NuGet

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup do .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependências
        run: dotnet restore
      
      - name: Build do projeto
        run: dotnet build --configuration Release --no-restore

      - name: Executar Testes
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Pack com Versionamento Automático
        run: dotnet pack ./Src/Exkyn.Notifications.Email/Exkyn.Notifications.Email.csproj --configuration Release --no-build -p:PackageVersion=1.0.${{ github.run_number }} --output ./nupkg

      - name: Obter token temporário do NuGet
        if: github.event_name == 'push'
        id: nuget_login
        uses: NuGet/login@v1
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Push para o NuGet.org
        if: github.event_name == 'push'
        run: dotnet nuget push ./nupkg/*.nupkg --api-key "${{ steps.nuget_login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate